config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  resources :posts do
    resources :comments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:"posts#index"
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # can :read, Post, public: true

    can :read, :all
    can :manage, Comment

    if user.present?  # additional permissions for logged in users (they can read their own posts)
     # can :read, Post, user_id: user.id


     if user.is_author?
       can :manage, Post
     end

     if user.is_admin?
       can :manage, :all
     end

     # if user.try (:admin)  # additional permissions for administrators
     #   can :manage, :all
     # else
     #   can :read, :all
     # end
   end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable


  def is_author?
    role == 'author'
  end

  def is_admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  check_authorization unless: :devise_controller? 
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html' }
      format.html { redirect_to main_app.root_url, notice: exception.message }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.save
    redirect_to post_path(@comment.post)
  end

def destroy
  @comment.destroy
  respond_to do |format|
    format.html { redirect_to post_url, notice: 'Post was successfully destroyed.' }
    format.json { head :no_content }
  end
end

  def comment_params
  params.require(:comment).permit(:title, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  # GET /posts
  # GET /posts.json
  def index
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
    @comment.post_id = @post.id
  end

  # GET /posts/new
  def new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end

end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  devise_for :users, controllers: { sessions: 'users/sessions' }
  def create
    # custom sign-in code
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<h5>Post a Comment</h5> <br/>
<div class='write_comment'>
  <%= form_for [ @post, @comment ] do |form| %>

  <div class="field">
    <%= form.label :user_id, 'Hey,' %> <br/>
    <% if current_user == nil %>
      <%= form.text_field :title %>
      <% else %>
    <%= User.find(@post.user_id).email %>
    <% end %>
  </div>
  <br/>

  <div class="field">
    <%= form.label :Comment_here %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChallengeBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="head_bar">
      <% if current_user == nil %>
        <%= link_to 'Log in', new_user_session_path, method: :get %>
        <pre> Der Vesputi Challenge Blog </pre>
      <% else %>
        Hallo <%= current_user.email %>(<%= current_user.role%>)<%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'warning' %>
        <pre> Der Vesputi Challenge Blog </pre>
      <% end %>
    </div>
    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_comment.html.erb
<section>
  <h3>Comment from <%= comment.title %></h3>
  <p class="comment"><%= comment.body %></p>
  <p> Posted <%= distance_of_time_in_words(comment.post.created_at, comment.created_at)%> after Post was created </p>
</section>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/comment.html.erb
<h1>Write Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @post %>
<%= link_to 'Back', posts_path %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %>
<%= link_to 'Back', posts_path %>
<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th style='font-size: 25px'>Title</th>
      <th style='font-size: 25px'>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post %></td>
        <td><%= post.user.email %> </td>
        <td><%= link_to 'Edit', edit_post_path(post) if can? :edit, post %> </td>
        <td><%= link_to('Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'warning') if can? :destroy, post %> </td>
       </tr>
    <% end %>
  </tbody>
</table>

<br>


<a href="/posts/new" style="margin-left: 7px;">New Post</a>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @post.title %>
</h1>

<p
  style="font-size:16px"><u> Written by:</u> <%= User.find(@post.user_id).email %>
</p>

<p>
  <%= simple_format @post.body %>
</p>
<br/>

<%= link_to 'Edit', edit_post_path(@post)if can? :edit, @post%>
<%= link_to 'Back', posts_path %>
<h2> Comments (<%= @post.comments.size %>)</h2>
<%= render partial: 'posts/comment', collection: @post.comments.reverse %>
<%= render partial: 'comments/form' %>